using System;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Security.Principal;

namespace RandomFile
{
    class Program
    {
        static async Task Main(string[] args)
        {
            string imadir = Directory.GetCurrentDirectory();
            var list = Directory.GetFiles(imadir);
            Console.WriteLine("Сколько?");
            string tmp_console_line = Console.ReadLine();
            int count = Convert.ToInt32(tmp_console_line==""?10:tmp_console_line);

            Now NOT WORK! AZAZAZ! MUHAHA!


            var numbers = await UseRandomOrgGenerateIntegers_1(count, list.Length, 1);

            string DesktopPath = Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory);

            DateTime Now = DateTime.Now;
            string dir = DesktopPath + "\\_autogenerated " + Now.ToShortDateString() + " " + Now.ToLongTimeString().Replace(':','_');
            Directory.CreateDirectory(dir);

            for (int i = 0; i < list.Length; i++)
            {

                if (numbers.Contains<int>(i+1))
                {
                    // Use the Path.Combine method to safely append the file name to the path.
                    // Will overwrite if the destination file already exists.
                    File.Copy(list[i], Path.Combine(dir, list[i].Substring(imadir.Length + 1)), true);

                }
            }

        }


        static public async Task<int[]> UseRandomOrgGenerateIntegers_1(int n, int max, int min)
        {

            //rm.Error = 1;
            //rm.Message = "Рандом был начат, но что-то пошло не так";
            //string jsonText = "{ \"jsonrpc\": \"2.0\", \"method\": \"generateIntegers\", \"params\": { \"apiKey\": \"00d79163-e0e4-405d-ba4e-859df106d6eb\", \"n\": 6, \"min\": 1, \"max\": 6, \"replacement\": true}, \"id\": 42}";
            //HttpWebRequest request = (HttpWebRequest)WebRequest.Create("https://api.random.org/json-rpc/2/invoke");
            string myJson = $"{{ \"jsonrpc\": \"2.0\", \"method\": \"generateIntegers\", \"params\": {{ \"apiKey\": \"00d79163-e0e4-405d-ba4e-859df106d6eb\", \"n\": {n}, \"min\": {min}, \"max\": {max}, \"replacement\": false}}, \"id\": 0}}";
            using (var client = new HttpClient())
            {
                var response = await client.PostAsync(
                    "https://api.random.org/json-rpc/2/invoke",
                     new StringContent(myJson, Encoding.UTF8, "application/json"));
                var result = await response.Content.ReadAsStringAsync();

                //rm.Error = 2;
                //rm.Message = "Ответ от random.org:\n";
                //rm.Message += result;

                int op = 0, ed = 0;
                for (int a = 0; result[a] != '\0'; a++)
                {
                    if (result[a] == '[')
                    {
                        op = a;
                        while (result[a] != ']')
                            a++;
                        ed = a;
                        break;
                    }
                }
                string charmass = result.Substring(op + 1, ed - op - 1);
                int[] mass = charmass.Split(',').Select(N => Convert.ToInt32(N)).ToArray();



                //rm.Error = 0;
                return mass;
            }
        }

    }
}
